### ISSUE TITLE
cancellation Status is 1 instead of CANCELLED

### ISSUE THREAD

**Issue by alvmunoz** [hotelbeds-sdk/hotel-api-sdk-Net#12]
As stated in issue #7 : 

Cancellation status is "1", instead of "CANCELLED": 

> But status is "1". Not a "CANCELLED".
> 
> [2016-04-19 20:11:25.8511][AkasakaTest.Button1_Click] ** cancel param ** 
> [2016-04-19 20:11:25.8511][AkasakaTest.Button1_Click] [
>   {
>     "Item1": "${bookingId}",
>     "Item2": "264-421111"
>   },
>   {
>     "Item1": "${flag}",
>     "Item2": "CANCELLATION"
>   }
> ] 
> [2016-04-19 20:11:25.8511][AkasakaTest.Button1_Click] ** bookingCancellationRS ** 
> [2016-04-19 20:11:25.8611][AkasakaTest.Button1_Click] {
>   "booking": {
>     "reference": "264-421111",
>     "cancellationReference": "GMOBEUNQCK",
>     "clientReference": "SDK TEST",
>     "creationDate": "2016-04-19T00:00:00",
>     "status": 1,
>     "holder": {
>       "name": "ROSETTA",
>       "surname": "PRUEBAS"
>     },
>     "hotel": {
>       "checkIn": "2016-07-28T00:00:00",
>       "checkOut": "2016-07-30T00:00:00",
>       "code": 49921,
>       "name": "Aqua Palms Waikiki",
>       "categoryCode": "3EST",
>       "categoryName": "3 STARS",
>       "destinationCode": "KAE",
>       "destinationName": "Hawaii - Oahu - HI",
>       "zoneCode": 4,
>       "zoneName": "Waikiki Beach / Honolulu",
>       "latitude": "21.284813297582744",
>       "longitude": "-157.83649428980425",
>       "rooms": [
>         {
>           "status": 1,
>           "code": "DBL.WV",
>           "paxes": [
>             {
>               "roomId": 1,
>               "type": "AD"
>             },
>             {
>               "roomId": 1,
>               "type": "CH"
>             }
>           ],
>           "rates": [
>             {
>               "rateComments": "Extra beds on demand YES FEE: NO. Check-in hour 15:00 – . ",
>               "paymentType": "AT_WEB",
>               "boardCode": "RO",
>               "boardName": "ROOM ONLY",
>               "rooms": 1,
>               "rateClass": "NOR"
>             }
>           ]
>         },
>         {
>           "status": 1,
>           "code": "DBL.WV",
>           "paxes": [
>             {
>               "roomId": 1,
>               "type": "AD"
>             },
>             {
>               "roomId": 1,
>               "type": "CH"
>             }
>           ],
>           "rates": [
>             {
>               "rateComments": "Extra beds on demand YES FEE: NO. Check-in hour 15:00 – . ",
>               "paymentType": "AT_WEB",
>               "boardCode": "RO",
>               "boardName": "ROOM ONLY",
>               "rooms": 1,
>               "rateClass": "NOR"
>             }
>           ]
>         }
>       ],
>       "currency": "JPY",
>       "supplier": {
>         "name": "HOTELBEDS USA INC",
>         "vatNumber": "592952685"
>       }
>     },
>     "remark": "***SDK***TESTING"
>   },
>   "auditData": {
>     "processTime": "2248",
>     "timestamp": "2016-04-19 13:11:24.688",
>     "requestHost": "118.238.248.165",
>     "serverId": "sa37AUX3ROLBLIS.env",
>     "environment": "[int]",
>     "release": "2cb1bad878d2195c9b508e2007ef96616007dacb"
>   }
> } 
> 
> Documentation of Booking Cancellation Response:
> 
> bookingCancellationRS/hotel/rooms/room/@status
> string
> Booking status:
> •CONFIRMED
> •CANCELLED
>

**Comment by alvmunoz** [comment]
@Akasaka-win, 
The information returned is correct but when you do the serialization it becomes "1" instead. 
I am not sure on how you are doing the serioalization, but here you have 2 different solutions I found in stackoverflow: 

> In case anyone wants to avoid attribute decoration, you can add the converter to your JsonSerializer: serializer.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter()); and it will work for every enum it sees during that serialization. 
> And with JsonConvert: JsonConvert.SerializeObject(MyObject, new Newtonsoft.Json.Converters.StringEnumConverter());

You can do that when you print your message to display "CANCELLATION".  

Additionally, I have made a change so "CANCELLATION" is displayed correctly without you having to do any change at your end.  I did the pull request, but it will take time until it is in the NuGet package. Still, you can try with the previous solution in the mean time.

**Comment by Akasaka-win** [comment]
"flag"はリファレンスに従う必要があったので、"status"も従うべきかと思いました。
"status=１" が "CANCELLED" を意味するというのであれば問題ありません。
ありがとうございました。

"flug" had to follow the reference.
So I thought I should also follow "status".
"status=1" means "CANCELLED". no problem. Thank you.

**Comment by Akasaka-win** [comment]
I was serialized in this way (Is as demo program).

```
BookingCancellationRS bookingCancellationRS = client.Cancel(param);
if (bookingCancellationRS != null)
{
    Console.WriteLine(JsonConvert.SerializeObject(bookingCancellationRS, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));
    :
    :
```

**Comment by alvmunoz** [comment]
You need to add the StringEnumConvert to your converters in order to make the serializer understand that 1 must be serialized as "CANCELLED". 

Following your code, that's one way to do it: 

```
BookingCancellationRS bookingCancellationRS = client.Cancel(param);
if (bookingCancellationRS != null)
{
            IList<JsonConverter> converters = new List<JsonConverter>();
            converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
            Console.WriteLine(JsonConvert.SerializeObject(bookingCancellationRS, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore, Converters = converters }));    
:
```

I did a dummy CancelationRS and it worked for me:

```
            BookingCancellationRS cancel = new BookingCancellationRS();
            com.hotelbeds.distribution.hotel_api_model.auto.model.Booking booking = new com.hotelbeds.distribution.hotel_api_model.auto.model.Booking();
            booking.status = com.hotelbeds.distribution.hotel_api_model.auto.common.SimpleTypes.BookingStatus.CANCELLED;
            cancel.booking = booking;
            Console.WriteLine("Serialization without StringEnumConverter:");
            Console.WriteLine(JsonConvert.SerializeObject(cancel, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));

            IList<JsonConverter> converters = new List<JsonConverter>();
            converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());

            Console.WriteLine("Serialization WITH StringEnumConverter:");
            Console.WriteLine(JsonConvert.SerializeObject(cancel, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore, Converters = converters }));
```

Result: 

![image](https://cloud.githubusercontent.com/assets/17126683/14703564/be07118e-07b0-11e6-988b-edeb4d8fb189.png)
