### ISSUE TITLE
about hotel-content-api/1.0/hotels

### ISSUE THREAD

**Issue by Akasaka-win** [hotelbeds-sdk/hotel-api-sdk-Net#16]
2016-4-16と2016-5-6のhotelsの結果でXMLの構造が異なります。
お手数ですが確認をお願いします。

**Comment by Akasaka-win** [comment]
ファイルが添付できるかと思いましたが、できませんでした。
圧縮したものをメールで送ります。

**Comment by alvmunoz** [comment]
恐らくアカウントの設定です。
SDKの問題ではないので閉めます。
