### ISSUE TITLE
error while running demo test

### ISSUE THREAD

**Issue by dtkachov** [hotelbeds-sdk/hotel-api-sdk-Net#17]
just downloaded the source code and run the demo application, and it led me to the error

"Error: " + e.Message + " " + e.StackTrace	"Error: One or more errors occurred.    
		at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
		at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteApi[T,U](U request, HotelApiPathsBase path, List`1 param) in D:\\dev\\RouteHotel\\test\\hotelBeds\\hotel-api-sdk\\HotelApiClient.cs:line 259
		at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.Detail(List`1 param) in D:\\dev\\RouteHotel\\test\\hotelBeds\\hotel-api-sdk\\HotelApiClient.cs:line 199
		at com.hotelbeds.distribution.hotel_api_sdk_demo.Program.Main(String[] args) in D:\\dev\\RouteHotel\\test\\hotelBeds\\hotel-api-sdk-demo\\Program.cs:line 257

in general it looks like works, but fails while getting some booking details.

I would appreciate if you would check it to confirm this is not an issue and might be ignored

**Comment by alvmunoz** [comment]
hi @dtkachov , 
I downloaded and ran it and didn't get any problem. I see that the line were it crashes is: 
response = resp.Content.ReadAsAsync<T>().Result;
Maybe the connecction is being cut for a firewall or proxy?  
Do the rest of calls work for you? Do you retrieve Status and Availability ?

**Comment by dtkachov** [comment]
I would disregard any connectivity problem as it crashes either in my home and office network...

Also it does not crash on the same booking every time. It grabs few booking and crashes after different  number of booking requests.

Example of bookings where it crashed:
                102-6618399
		1-3179694
		102-6618395

Log example:
[log.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-Net/files/257879/log.txt)

**Comment by alvmunoz** [comment]
So everytime you try booking detail for any of these bookings it fails?  
Also, can you provide me your apikey?  (do not share your secret)

**Comment by dtkachov** [comment]
I think it fails randomly. Cases I provided are example if three subsequent runs where it failed for different bookings.

My API key is a4y9rcvdtngsn6fjqn4e56eb

**Comment by alvmunoz** [comment]
Could it be due a timeout?  Does it crash straigh away or after X seconds waiting for the response?

**Comment by dtkachov** [comment]
I doubt this is because of timeout, cause it in literally few seconds...

is there possibility to switch logs on to check more details?

**Comment by alvmunoz** [comment]
I think I am close to find the reason. 
Can you update the SDK ?   It should print now more information on the Exception you are receiving.  
If I am correct (and once you make the change it will show up) , you might be receiving as a response an HTML instead than a JSON.

**Comment by alvmunoz** [comment]
@dtkachov , this is happening because you have an Evaluation plan. This only allows you to make 1 call per second and 50 calls per day.  Whenever you exceed any of them, the server returns an HTML error message and that's why the code is crashing.

**Comment by alvmunoz** [comment]
If you want to increase your plan, please contact apitude@hotelbeds.com
