### ISSUE TITLE
Compression: Encoding typo 

### ISSUE THREAD

**Issue by pmorelli-origin** [hotelbeds-sdk/hotel-api-sdk-Net#19]
Hi guys, there is a typo in the SDK, in the HotelClientApi class, where the request are not being sent with the **Accept-Encoding: gzip** but with **Accept-EncoNding: gzip**. With this problem the responses are not being compressed. This causes an overhead for your servers and for the clients due to the large responses. 

![error](https://cloud.githubusercontent.com/assets/12255242/16009326/908b3db8-3152-11e6-89e7-3b698fb56167.png)

I hope you can fix it soon.
Regards,
Pablo Morelli

**Comment by alvmunoz** [comment]
@pmorelli-origin  fixed!  Thanks!!

**Comment by pmorelli-origin** [comment]
That change is introducing an error when you do **resp.Content.ReadAsAsync<T>()** since the deserializer does not know that the response is compressed.

I made a pull request with the correct change, please if you merge build a new nuget package in order me to download it. 

#20 

Regards,
Pablo Morelli

**Comment by alvmunoz** [comment]
@jrossello , can you generate the nuget package please???

**Comment by pmorelli92** [comment]
@jrossello @alvmunoz any news on the new version of the package?

**Comment by alvmunoz** [comment]
@pmorelli-origin sorry for the delay. We updated nuget package to version 0.6 containing your changes. 
Also, I must mention that we changed our internal procedures to speed this process up. Next time we will update the nuget version 'on-the-fly' every time we make a change in github.
Thanks for your support
