### ISSUE TITLE
HotelApiClient Error

### ISSUE THREAD

**Issue by mohamedalyattia** [hotelbeds-sdk/hotel-api-sdk-Net#2]
i am using this code 
HotelApiClient client = new HotelApiClient();
StatusRS status = client.status();

if (status != null && status.error == null)
Response.Write("StatusRS: " + status.status);
else if (status != null && status.error != null)
{
Response.Write("StatusRS: " + status.status + " " + status.error.code + ": " + status.error.message);
return;
}
else if (status == null)
{
Response.Write("StatusRS: Is not available.");
return;
}

Availability avail = new Availability();
avail.checkIn = DateTime.Now.AddDays(10);
avail.checkOut = DateTime.Now.AddDays(13);
avail.destination = "PMI";
avail.zone = 90;
avail.language = "CAS";
AvailRoom room = new AvailRoom();
room.adults = 2;
room.children = 0;
room.details = new List<RoomDetail>();
room.adultOf(30);
room.adultOf(30);
//room.childOf(4);
avail.rooms.Add(room);
avail.payed = Availability.Pay.AT_HOTEL;

AvailabilityRQ availabilityRQ = avail.toAvailabilityRQ();
if (availabilityRQ == null)
throw new Exception("Availability RQ can't be null", new ArgumentNullException());

AvailabilityRS responseAvail = client.doAvailability(availabilityRQ);

if (responseAvail != null && responseAvail.hotels != null && responseAvail.hotels.hotels != null && responseAvail.hotels.hotels.Count > 0)
{
foreach (var hotel in responseAvail.hotels.hotels)
Response.Write(String.Format("Hotel Name: {0} Category Name: {1} Destination: {2} Rooms: {3}", hotel.name, hotel.categoryName, hotel.destinationName, hotel.rooms.Count));
}

and show this error :
HotelApiClient cannot be created without specifying an API key, Shared Secret, the Hotel API version and the service you are connecting to.

**Comment by pmayol** [comment]
Hi Mohamed

In order to test the SDK it is necessary to have an api-key and shared secret key. You can get them in https://developer.hotelbeds.com/

**Comment by mohamedalyattia** [comment]
i have already get the api-key and shared secret key from  my account ant using it in object initiation

HotelApiClient client = new HotelApiClient(new HotelApiVersion(HotelApiVersion.versions.V1),api-key , secret key )
but still show 
HotelApiClient cannot be created without specifying an API key, Shared Secret, the Hotel API version and the service you are connecting to.

**Comment by alvmunoz** [comment]
Hi @mohamedalyattia ,
You must replace your line:
HotelApiClient client = new HotelApiClient(new HotelApiVersion(HotelApiVersion.versions.V1),api-key , secret key )
by this:
        HotelApiClient client = new HotelApiClient();

And add the following code in the Web.config within the <configuration> tag:

  <appSettings>
    <add key="ApiKey" value="gfhpht2ffsfejd88g7pcnexe" />
    <add key="SharedSecret" value="e7Af9xbEtm" />
    <add key="ENVIRONTMENT" value="TEST" />
    <add key="TEST" value="https://api.test.hotelbeds.com/hotel-api" />
    <add key="LIVE" value="https://api.hotelbeds.com/hotel-api" />
    <add key="DEVELOPMENT" value="http://localhost:8181" />
  </appSettings>

**Comment by alvmunoz** [comment]
`  <appSettings>
    <add key="ApiKey" value="XXXX" />
    <add key="SharedSecret" value="XXXX" />
    <add key="ENVIRONTMENT" value="TEST" />
    <add key="TEST" value="https://api.test.hotelbeds.com/hotel-api" />
    <add key="LIVE" value="https://api.hotelbeds.com/hotel-api" />
    <add key="DEVELOPMENT" value="http://localhost:8181" />
  </appSettings>
`

replacing the XXX by your ApiKey and Sharedsecret

**Comment by mohamedalyattia** [comment]
OK it solved now
how i using this API to retrieve hotel content like Counties or Locations 
and i am using ARA for retrieve Arabic language but i still retrieve English data

**Comment by alvmunoz** [comment]
Hi,
For the time being our SDK only covers hotel-api. We already have plans to release another sdk for hotel-content-api. 

About the language, when we don't have content for the requested language, we return English as second language by default.
