### ISSUE TITLE
Error deserializing BookingRS

### ISSUE THREAD

**Issue by borisovalex** [hotelbeds-sdk/hotel-api-sdk-Net#21]
Hi,
when I try to make a booking using API demo app I get an error:

Message	"There was an error deserializing the object of type com.hotelbeds.distribution.hotel_api_model.auto.messages.BookingRS. The data at the root level is invalid. Line 1, position 1."	string

The error is on:
   response = resp.Content.ReadAsAsync<T>().Result;

The Response from API seems to be OK. I'm attaching booking Request and Response JSON 
BookingCheck and AvailabilityRQ run without issues.

[bookingRQ.json.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-Net/files/343189/bookingRQ.json.txt)
[bookingRS.json.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-Net/files/343188/bookingRS.json.txt)

**Comment by alvmunoz** [comment]
@borisovalex,  it was probably due a problem with the headers. Can you update the sdk and try again? 

Also, can you advise how did you get the bookingRS if the error was triggered in  resp.Content.ReadAsAsync().Result; ?   Did you read this response from the code?

**Comment by borisovalex** [comment]
Hi,
I've also found that the issue is in service response Content-Type and we created a ticket on aptitude.
Using fixed code for HotelApiClient , there is no more errors.
Thanks.
