### ISSUE TITLE
BookingRS - RateType is throwing an error when serializing

### ISSUE THREAD

**Issue by pmorelli92** [hotelbeds-sdk/hotel-api-sdk-Net#22]
Hi guys,

I have the necessity of logging all the booking request and response that I send to your SDK so if there is a problem I can see what the request and response were.

In order to log them in need to serialize them to a json string.
When I serialize the BookingRQ I have no problems but when I am serializing the BookingRS using 

```cs
Newtonsoft.Json.JsonConvert(bookingRS)
```

I get the following exception

```cs
Cannot write a null value for property 'rateType'. Property requires a value. Path 'hotel.rooms[0].rates[0]'
```

This is because the property basicRate.rateType has the required attribute and in the BookingRS the value is null.

So we have two options:

- You send the rateType in the BookingRS.
- We comment the attribute JsonProperty for the rateType.

I did the following change:

```cs
//[JsonProperty("rateType", Required = Required.Always)]
[JsonConverter(typeof(JSonConverters.RateTypeConverter))]
public SimpleTypes.RateType? rateType { get; set; }
```

And then tested using the Console provided and it all worked well (and now I can serialize the BookingRS to a json string)

Can we get this fix?

Thanks!

**Comment by pmorelli92** [comment]
Reference to the pull request #23

**Comment by alvmunoz** [comment]
I see, I didn't receive this error because I was ignoring nulls. I will accept your change because it is correct, but anyway, I recommend you to serialize ignoring nulls since it gives you clearer results: 

`JsonConvert.SerializeObject(response, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }); `

**Comment by pmorelli92** [comment]
@alvmunoz can we get a new minor upgrade in nuGet? Thanks!!

**Comment by alvmunoz** [comment]
@pmorelli92  Sorry, I thought you didn't need the package. Uploaded it as 0.6.2.

**Comment by pmorelli92** [comment]
@alvmunoz Thanks! :smiley:
