### ISSUE TITLE
About .NET platform English Doc. for HotelBeds SDK

### ISSUE THREAD

**Issue by hbdalgic** [hotelbeds-sdk/hotel-api-sdk-Net#24]
We need english documentation about this case. We sent emails about 2 days ago. We are waiting response. Soon as possible.

**Comment by alvmunoz** [comment]
Hi,
The documentation of this SDK in in the homepage: https://github.com/hotelbeds-sdk/hotel-api-sdk-Net
While the documentation in English about the API is in our developer portal: https://developer.hotelbeds.com/docs 

Regards,
