### ISSUE TITLE
About How Get Images from SDK

### ISSUE THREAD

**Issue by gkhntzr** [hotelbeds-sdk/hotel-api-sdk-Net#25]
We want to get image from HotelApiClient. 

Which function get & set image data.

**Comment by gkhntzr** [comment]
Do you write wiki doc. when you develop this system.

**Comment by alvmunoz** [comment]
Hi, 
Althought we plan to include ContentAPI in future,  currently this SDK only supports BookingAPI.   
You can refer to our documention on how to do it: 
https://developer.hotelbeds.com/docs/read/APITUDE_CONTENT

**Comment by gkhntzr** [comment]
Ok. But in this case how can we sell the otels, and tours.

how can we find hotels images ?

**Comment by gkhntzr** [comment]
Ok. But in this case how can we sell the otels, and tours.


how can we find hotels images ?

    

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

Date: Thu, 21 Jul 2016 03:09:41 -0700

**Comment by alvmunoz** [comment]
You need to integrate both BookingAPI and ContentAPI to achieve that. 
Please, use github only to ask questions related to the use of the SDK. 
Regards,

**Comment by gkhntzr** [comment]
Ok. How can we integrate both BookingAPI & ContentAPI.

Your documentation's so bad.

Why are you evading my question?

Why do not you help?

Your SDK not stable right now for .net platforms.

**Comment by alvmunoz** [comment]
Can you specify what's not stable in the .net SDK?  Did you find any bug?
