### ISSUE TITLE
Add Hotel Image About Content api

### ISSUE THREAD

**Issue by gkhntzr** [hotelbeds-sdk/hotel-api-sdk-Net#26]
How can we add image. For example in your documentation's

http://photos.hotelbeds.com/giata/    + path.

When we add the .net. Path isnt return.

**Comment by alvmunoz** [comment]
Hi,
As I said before,  this SDK is only for HotelAPI/BookingAPI, but it doesn't include ContentAPI.

**Comment by gkhntzr** [comment]
Ok. I understood.  When i access ContentAPI ?

**Comment by alvmunoz** [comment]
We don't have a relase date for our ContentAPI in this SDK yet.  In the meantime, you can access the ContentAPI directly through our API.

**Comment by gkhntzr** [comment]
Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

Date: Mon, 25 Jul 2016 06:53:54 -0700

**Comment by gkhntzr** [comment]
Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.
Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:17:39 +0000




Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

Date: Mon, 25 Jul 2016 06:53:54 -0700

**Comment by gkhntzr** [comment]
Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:17:56 +0000





Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.
Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:17:39 +0000




Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

Date: Mon, 25 Jul 2016 06:53:54 -0700

**Comment by gkhntzr** [comment]
Dear Alvaro

Thanks your answers. 
We talked with your Turkey agent Mrs. Tuba Kirli.
We want to use your XML system. 
We give up Apitude,when you will finish ContentAPİ.
Mr. Daniel send emails about xml systems but your links not working.
And links give some errors. We attach the error screen.
In this time; we need hotels data bu we cant access. 
How can we access hotel data with your xml sys. 
For Example ; What is your destinations code, zone code. 
How it works your search algoritm.
Your documentation is not enough and last one please.
What are the examples made ​​using your structure?

Best Regards...
Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:18:08 +0000




              

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:17:56 +0000





Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.
Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

From: gokhan_tezer@hotmail.com
To: reply@reply.github.com
Subject: RE: [hotelbeds-sdk/hotel-api-sdk-Net] Add Hotel Image About Content api (#26)
Date: Tue, 26 Jul 2016 11:17:39 +0000




Dear Alvaro

Thanks your answers. 
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.

Gökhan TEZER / Computer Engineer

www.gokhantezer.com.tr / + 90 554 686 58 54

Date: Mon, 25 Jul 2016 06:53:54 -0700

**Comment by alvmunoz** [comment]
Please, contact apitude@hotelbeds.com
