### ISSUE TITLE
Image problem 

### ISSUE THREAD

**Issue by hbdalgic** [hotelbeds-sdk/hotel-api-sdk-Net#27]
http://photos.hotelbeds.com/giata/02/024838/024838a_hb_ro_018.jpg ,imagine that we have this link. how can i get "02/024838/024838a_hb_ro_018.jpg" this path?

**Comment by alvmunoz** [comment]
Hi, 
This SDK is only for BookingAPI, it doesn't include the images which are in ContentAPI. 
Regards,
