### ISSUE TITLE
About XML Systems

### ISSUE THREAD

**Issue by gkhntzr** [hotelbeds-sdk/hotel-api-sdk-Net#29]
Dear Alvaro

Thanks your answers.
We talked with your turkey agent Mrs. Tuba Kirli.
We want to use your XML system.
Mr. Daniel send emails about xml systems but your links not working.
And Links give some errors. We attach the error screen.
In this time we need hotels data bu we cant access. How can we access with your xml sys.

**Comment by alvmunoz** [comment]
Please, use github only for SDK related questions or issues. 
For any other matter, contact apitude@hotelbeds.com
