### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by chen131036** [hotelbeds-sdk/hotel-api-sdk-Net#3]
I download the demo from here.But when I run it,I can't get data.This code responseAvail.hotels equals null.So I need your help

**Comment by alvmunoz** [comment]
@chen131036 , you will receive a null response if the server timed out (that is, response slower than 60 seconds).  Is that your case?

**Comment by chen131036** [comment]
@alvmunoz I don't think it is.I didn't change anywhere,but today I get some data.It's so strange

**Comment by alvmunoz** [comment]
@chen131036  that's what I mean. If the server sends you timeout, you receive a null answer. If the server does not timeout then it will be correct.

**Comment by chen131036** [comment]
OK,I will have a try.

**Comment by alvmunoz** [comment]
@chen131036 , did it work for you?
