### ISSUE TITLE
checkratesRQ - application/xml 

### ISSUE THREAD

**Issue by mohebbi310** [hotelbeds-sdk/hotel-api-sdk-Net#32]
hi,
I send request for checkrate but i have error message 👍 
`Invalid data. Error at property rooms: property size must be between 1 and 2147483647`
my request

```
<q1:checkRateRQ xmlns:q1="http://www.hotelbeds.com/schemas/messages">
  <q1:rooms>
    <q1:paxes>
      <q1:pax type="AD" age="30" name="Nombre" surname="Apelli" />
    </q1:paxes>
    <q1:rateKey>20161015|20161016|W|77|233475|SGL.EY|B2C NRF|BB||1~1~0||N@06D8DF50E3FC422C908F030087F5465D</q1:rateKey>
  </q1:rooms>
</q1:checkRateRQ>
```

You can tell the meaning of this message, please.
Thank you for your attention to this matter.
Regards.

**Comment by alvmunoz** [comment]
hi @mohebbi310 , the correct structure of the checkRates if the following:

> <checkRateRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" upselling="true" language="ENG">
>   <rooms>
>     <room rateKey="20161219|20161220|W|235|156416|APT.B3|GC-ALL1|SC||2~2~1|4|N@F0B155DCF58E40C19FDE6F889CA8B664"/>
>   </rooms>
> </checkRateRQ>
