### ISSUE TITLE
Status Code 403 - Forbidden

### ISSUE THREAD

**Issue by pmorelli92** [hotelbeds-sdk/hotel-api-sdk-Net#33]
Hi guys, I am having a problem when doing requests using the SDK.
I checked if the error was in my integration but it happens as well in the SDK test console.
Whenever I do a request I am getting the Status Code 403, however if I do the same request from the sandbox I am getting an Status Code = 200 OK.

For example, request:

```json
{
	"Method": "POST",
	"RequestUri": "https://api.test.hotelbeds.com/hotel-api/1.0/hotels",
	"Version": "1.1",
	"Content": "System.Net.Http.StringContent",
	"Headers": {
		"Api-Key": "wbxrv2d759hmvh4b4wu6jxyu",
		"X-Signature": "6EC60F58AEDED06D3D3680C5545A68A1AFA527E12BBC636338D21609A61573B2",
		"Accept": "application/json",
		"Content-Type": "application/json; charset=utf-8",
		"Content-Length": 773
	}
}
```

Response:

```json
{
	"StatusCode": 403,
	"ReasonPhrase": "Forbidden",
	"Version": "1.1",
	"Content": "System.Net.Http.StreamContent",
	"Headers": {
		"X-Error-Detail-Header": "Not Authorized",
		"X-Mashery-Error-Code": "ERR_403_NOT_AUTHORIZED",
		"X-Mashery-Responder": "prod-j-worker-eu-west-1c-61.mashery.com",
		"Connection": "keep-alive",
		"Date": "Tue, 04 Oct 2016 14:08:22 GMT",
		"Server": "Mashery",
		"Server": "Proxy",
		"Content-Length": 23,
		"Content-Type": "text/xml"
	}
}
```

Thanks,
Regards,
Pablo Morelli

**Comment by alvmunoz** [comment]
hi @pmorelli92 ,

It must be related with the creation of the X-Signature.  I checked your apikey and it is working properly.

Have you modified your X-Signature?  I can see it is all uppercaps but normally it isn't.
An example of a  working x-signature: 1e5fc5c715522ad543d9c5b27b24100a02730cb24ec71c328ef792028d859f21

**Comment by pmorelli92** [comment]
Hi @alvmunoz 

I was unable to respond sooner.
Thanks for the info, the problem was that the server time was behind a few minutes, then the generated hash was invalid.

Thanks!
