### ISSUE TITLE
Required property 'type' not found in JSON

### ISSUE THREAD

**Issue by alvmunoz** [hotelbeds-sdk/hotel-api-sdk-Net#34]
Case. 04761517

We are getting issue when De-Serializing CheckRateRS, as “type” property is not there. From what I see on git hub code , it is a required property

https://github.com/hotelbeds-sdk/hotel-api-sdk-Net/blob/master/hotel-api-model/auto/model/Tax.cs

===============
[JsonProperty("type", Required = Required.Always)]
[JsonConverter(typeof(JSonConverters.TaxTypeConverter))]
public SimpleTypes.TaxType type { get; set; }

===============

Error
Newtonsoft.Json.JsonSerializationException: Required property 'type' not found in JSON. Path 'hotel.rooms[0].rates[0].taxes.taxes[0]', line 1

Request

"{\"rooms\":[{\"paxes\":[{\"type\":\"AD\",\"age\":21},{\"type\":\"AD\",\"age\":21}],\"rateKey\":\"20161030|20161031|W|228|9353|DBL.SU|NRF-698PROMO18|BB||1~2~0||N@CE00F2572E8A45A496264856F65FF960\"}]}"

Response

"{\"auditData\":{\"processTime\":\"779\",\"timestamp\":\"2016-10-06 08:33:27.747\",\"requestHost\":\"121.244.27.226\",\"serverId\":\"sa3RKSJACHXE79K.env\",\"environment\":\"[int]\",\"release\":\"c71dde3dff5b7361b72a269a2d41e85a1aa34be0\",\"internal\":\"2ja84u6t9myz2cwhtp99e2pt|UK|01||25|118|1|7|8|N|null,null||||||||1\"},\"hotel\":{\"checkIn\":\"2016-10-30\",\"checkOut\":\"2016-10-31\",\"code\":9353,\"name\":\"NH Salzburg City\",\"categoryCode\":\"4EST\",\"categoryName\":\"4 STARS\",\"destinationCode\":\"SZG\",\"destinationName\":\"Salzburg\",\"zoneCode\":1,\"zoneName\":\"Salzburg\",\"latitude\":\"47.805487\",\"longitude\":\"13.048672\",\"rooms\":[{\"code\":\"DBL.SU\",\"name\":\"DOUBLE SUPERIOR\",\"rates\":[{\"rateKey\":\"20161030|20161031|W|228|9353|DBL.SU|NRF-698PROMO18|BB||1~2~0||N@CE00F2572E8A45A496264856F65FF960\",\"rateClass\":\"NRF\",\"rateType\":\"BOOKABLE\",\"net\":\"115.52\",\"sellingRate\":\"129.80\",\"hotelMandatory\":true,\"rateComments\":\"No amendments or cancellations will be accepted once bookings are made under this non-refundable promotion Estimated total amount of taxes & fees for this booking:2.20 Euro payable on arrival. \",\"paymentType\":\"AT_WEB\",\"packaging\":false,\"boardCode\":\"BB\",\"boardName\":\"BED AND BREAKFAST\",\"cancellationPolicies\":[{\"amount\":\"115.52\",\"from\":\"2016-10-05T23:59:00+02:00\"}],\"taxes\":{\"taxes\":[{\"included\":false,\"amount\":\"2.20\",\"currency\":\"EUR\",\"clientAmount\":\"2.20\",\"clientCurrency\":\"EUR\"}],\"allIncluded\":false},\"rateBreakDown\":{\"rateSupplements\":[{\"code\":\"SR\",\"name\":\"BOARD SUPPLEMENT\",\"from\":\"2016-10-30\",\"to\":\"2016-10-31\",\"amount\":\"26.52\",\"nights\":1,\"paxNumber\":2}]},\"rooms\":1,\"adults\":2,\"children\":0}]}],\"totalNet\":\"115.52\",\"currency\":\"EUR\",\"upselling\":{\"rooms\":[{\"code\":\"DBL.SU\",\"name\":\"DOUBLE SUPERIOR\",\"rates\":[{\"ra

**Comment by akharsh-tr** [comment]
Hi There,
Any update on the issue?

**Comment by alvmunoz** [comment]
Hi @akharsh-tr , can you show me the line where you serializating the object? 

I sent your very same request and I am not having any error despite of not receiving the type.

![captura](https://cloud.githubusercontent.com/assets/17126683/19597209/78a5b3ca-9793-11e6-9c03-87ac6a347dd6.png)

That's how I am doing the serialization: 

JsonConvert.SerializeObject(checkRatesResponse, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore });

**Comment by alvmunoz** [comment]
@akharsh-tr  oh sorry, I didn't realize you were speaking about **DE**serialization  I didn't realize since normally everyone wants to make serialization but normally deserialization is not needed. 

I will change it so it is not a mandatory field as you point.
