### ISSUE TITLE
The CheckIn and ChecKOut dates are missing at response of 'Details'

### ISSUE THREAD

**Issue by dmonsilver** [hotelbeds-sdk/hotel-api-sdk-Net#36]
Hello,

The Checkin and CheckOt dates seems to be absent  at detail response.

I.e:

{
  "reference": "102-7108572",
  "cancellationReference": null,
  "clientReference": "EXP DE LA AGENCIA",
  "creationDate": "2016-10-14T00:00:00",
  "status": "CONFIRMED",
  "agCommision": 0.0,
  "commisionVAT": 0.0,
  "creationUser": null,
  "holder": {
    "name": "dmonsilver",
    "surname": "dmonsilver"
  },
  "hotel": {
    "code": 550,
    "name": "San Pablo",
    "categoryCode": "3EST",
    "categoryName": "3 STARS",
    "destinationCode": "SVQ",
    "destinationName": "Seville",
    "zoneCode": 99,
    "zoneName": "Sevilla",
    "latitude": "37.405399",
    "longitude": "-5.92755",
    "giata": null,
    "keywords": null,
    "reviews": null,
    "rooms": [
      {
        "status": "CONFIRMED",
        "code": "DBL.DB",
        "name": "DOUBLE DOUBLE BED",
        "paxes": [
          {
            "roomId": 1,
            "type": "AD",
            "age": null,
            "name": "David",
            "surname": "Montano Silva"
          },
          {
            "roomId": 1,
            "type": "AD",
            "age": null,
            "name": "dmonsilver",
            "surname": "dmonsilver"
          }
        ],
        "rates": [
          {
            "rateName": null,
            "rateCommentsId": null,
            "rateComments": "Key Collection 15:00 ? 05:00. Check-in hour 15:00 ? 05:00. . Parking under request and extra fee",
            "paymentType": "AT_WEB",
            "packaging": false,
            "boardCode": "RO",
            "boardName": "ROOM ONLY",
            "cancellationPolicies": [
              {
                "amount": 36.67,
                "hotelAmount": 0.0,
                "hotelCurrency": null,
                "from": "2017-07-28T12:00:00+02:00"
              }
            ],
            "taxes": null,
            "rateBreakDown": null,
            "rooms": 1,
            "adults": 0,
            "children": 0,
            "childrenAges": null,
            "promotions": null,
            "offers": null,
            "shiftRates": null,
            "rateup": 0.0,
            "rateKey": null,
            "rateClass": "NOR",
            "rateType": null,
            "net": 36.67,
            "discount": 0.0,
            "discountPCT": 0.0,
            "sellingRate": 39.90,
            "hotelSellingRate": 0.0,
            "amount": 0.0,
            "hotelCurrency": null,
            "hotelMandatory": true,
            "dailyRates": null,
            "allotment": 0,
            "commission": 0.0,
            "commissionVAT": 0.0,
            "commissionPCT": 0.0
          }
        ]
      }
    ],
    "minRate": 0.0,
    "maxRate": 0.0,
    "totalSellingRate": 0.0,
    "totalNet": 36.67,
    "pendingAmount": 0.0,
    "currency": "EUR",
    "creditCards": null,
    "supplier": {
      "name": "HOTELBEDS PRODUCT,S.L.U.",
      "vatNumber": "ESB38877676"
    },
    "clientComments": null,
    "upselling": null
  },
  "remark": "Notas"
}

**Comment by alvmunoz** [comment]
Thank you, we are adding it.
