### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by akharsh-tr** [hotelbeds-sdk/hotel-api-sdk-Net#37]
Hi, 

How often you guys create nuget release ?
I raised one issue which has been resolved so looking for package.

Regards
A

**Comment by alvmunoz** [comment]
Hi @akharsh-tr , 
We do it within one week of fixing the issue.
About that issue you raised, we will try to release it today.

**Comment by alvmunoz** [comment]
We released it today as version 6.0.3 today
