### ISSUE TITLE
Booking with same RateKey

### ISSUE THREAD

**Issue by akharsh-tr** [hotelbeds-sdk/hotel-api-sdk-Net#38]
Sample Occupancies -
"occupancies": [
        {
            "rooms": 1,
            "adults": 2,
            "children": 0,
            "paxes": [
                {
                    "type": "AD",
                    "age": 21
                },
                {
                    "type": "AD",
                    "age": 21
                }
            ]
        },
        {
            "rooms": 1,
            "adults": 2,
            "children": 0,
            "paxes": [
                {
                    "type": "AD",
                    "age": 21
                },
                {
                    "type": "AD",
                    "age": 21
                }
Sample rate Key -

"rateKey": "20161101|20161105|W|228|6335|DBT.ST|CG-BAR|BB||1~2~0||N@CAD5CD92DB634DCAA979E7690A1EDBBC"

Now I want to book with these rate keys -
Booking request

{
    "holder": {
        "name": "FirstName",
        "surname": "LastName"
    },
    "rooms": [
        {
            "rateKey": "20161101|20161105|W|228|6335|DBT.ST|CG-BAR|BB||1~2~0||N@CAD5CD92DB634DCAA979E7690A1EDBBC",
            "paxes": [
                {
                    "roomId": "1",
                    "type": "AD",
                    "age": 30,
                    "name": "First Adult Name",
                    "surname": "Surname"
                },
                {
                    "roomId": "1",
                    "type": "AD",
                    "age": 30,
                    "name": "Second Adult Name",
                    "surname": "Surname"
                },
                {
                    "roomId": "2",
                    "type": "AD",
                    "age": 30,
                    "name": "First Adult Name",
                    "surname": "Surname"
                },
                {
                    "roomId": "2",
                    "type": "AD",
                    "age": 30,
                    "name": "Second Adult Name",
                    "surname": "Surname"
                }
            ]
        }
    ],
    "clientReference": "test"
}

it throws error -
"message": "Invalid data. Error at property rooms: The distribution of paxes is not correct. The number of rooms specified in the paxes do not match with the requested ones"

I tried changing roomId also but no help.

**Comment by alvmunoz** [comment]
The correct way to do it is the following: 

{
"holder": {
"name": "FirstName",
"surname": "LastName"
},
"rooms": [
{
"rateKey": "20161101|20161105|W|228|6335|DBT.ST|CG-BAR|BB||1~2~0||N@CAD5CD92DB634DCAA979E7690A1EDBBC",
"paxes": [
{
"roomId": "1",
"type": "AD",
"age": 30,
"name": "First Adult Name",
"surname": "Surname"
},
{
"roomId": "1",
"type": "AD",
"age": 30,
"name": "Second Adult Name",
"surname": "Surname"
}
]
},
{
"rateKey": "20161101|20161105|W|228|6335|DBT.ST|CG-BAR|BB||1~2~0||N@CAD5CD92DB634DCAA979E7690A1EDBBC",
"paxes": [
{
"roomId": "1",
"type": "AD",
"age": 30,
"name": "First Adult Name",
"surname": "Surname"
},
{
"roomId": "1",
"type": "AD",
"age": 30,
"name": "Second Adult Name",
"surname": "Surname"
}
]
}
],
"clientReference": "test"
}

**Comment by akharsh-tr** [comment]
Just tried this- 
{
    "holder": {
        "name": "John",
        "surname": "Travolta"
    },
    "rooms": [
        {
            "paxes": [
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "John",
                    "surname": "Travolta"
                },
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "Guest",
                    "surname": "Two"
                }
            ],
            "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@2D42E5E2F9A849619FA029FEEFCF48B3"
        },
        {
            "paxes": [
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "John",
                    "surname": "Travolta"
                },
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "Guest",
                    "surname": "Four"
                }
            ],
            "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@2D42E5E2F9A849619FA029FEEFCF48B3"
        }
    ],
    "clientReference": "test"
}
**Got Error -** 

 "message": "ProductException(d7aec2d8-329a-496a-9429-9e56ee8d8a08, AVAILABILITY_CONFIRM, There is not enough space in the service for all the passengers.)

**Comment by alvmunoz** [comment]
Check the room allotment. In case of having only one allotment you cannot book 2.

**Comment by akharsh-tr** [comment]
**Avail Response  Snippet :** allotment is 2

{
    "auditData": {
        "processTime": "1509",
        "timestamp": "2016-10-25 18:55:33.452",
        "requestHost": "121.244.27.226",
        "serverId": "sa37AUX3ROLBLIS.env",
        "environment": "[int]",
        "release": "c71dde3dff5b7361b72a269a2d41e85a1aa34be0",
        "internal": "2ja84u6t9myz2cwhtp99e2pt|UK|03|HA|1|2|null,null||BB,BB||||||1"
    },
    "hotels": {
        "hotels": [
            {
                "code": 199527,
                "name": "Alpha",
                "categoryCode": "3EST",
                "categoryName": "3 STARS",
                "destinationCode": "VIE",
                "destinationName": "Vienna",
                "zoneCode": 1,
                "zoneName": "Vienna",
                "latitude": "48.210438",
                "longitude": "16.353403",
                "rooms": [
                    {
                        "code": "TPL.ST",
                        "name": "TRIPLE STANDARD",
                        "rates": [
                            {
                                "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@0A55B41EDCCA4D38B553884175F4E546",
                                "rateClass": "NOR",
                                "rateType": "BOOKABLE",
                                "net": "347.32",
                                "allotment": 2,
                                "rateCommentsId": "228|6462|0",
                                "paymentType": "AT_WEB",
                                "packaging": false,
                                "boardCode": "BB",
                                "boardName": "BED AND BREAKFAST",
                                "cancellationPolicies": [
                                    {
                                        "amount": "347.32",
                                        "from": "2016-12-02T18:00:00+01:00"
                                    }
                                ],
                                "rooms": 1,
                                "adults": 2,
                                "children": 0
                            },
                            {
                                "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@0A55B41EDCCA4D38B553884175F4E546",
                                "rateClass": "NOR",
                                "rateType": "BOOKABLE",
                                "net": "347.32",
                                "allotment": 2,
                                "rateCommentsId": "228|6462|0",
                                "paymentType": "AT_WEB",
                                "packaging": false,
                                "boardCode": "BB",
                                "boardName": "BED AND BREAKFAST",
                                "cancellationPolicies": [
                                    {
                                        "amount": "347.32",
                                        "from": "2016-12-02T18:00:00+01:00"
                                    }
                                ],
                                "rooms": 1,
                                "adults": 2,
                                "children": 0
                            }
                        ]
                    }
                ],
                "minRate": "347.32",
                "maxRate": "347.32",
                "currency": "EUR"
            }
        ],
        "checkIn": "2016-12-03",
        "checkOut": "2016-12-04",
        "total": 1
    }
}

**Booking Requet**
{
    "holder": {
        "name": "John",
        "surname": "Travolta"
    },
    "rooms": [
        {
            "paxes": [
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "John",
                    "surname": "Travolta"
                },
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "Guest",
                    "surname": "Two"
                }
            ],
            "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@0A55B41EDCCA4D38B553884175F4E546"
        },
        {
            "paxes": [
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "John",
                    "surname": "Travolta"
                },
                {
                    "roomId": 1,
                    "type": "AD",
                    "age": 21,
                    "name": "Guest",
                    "surname": "Four"
                }
            ],
            "rateKey": "20161203|20161204|W|228|199527|TPL.ST|CG-BAR|BB||1~2~0||N@0A55B41EDCCA4D38B553884175F4E546"
        }
    ],
    "clientReference": "test"
}

**Booking Response**
{"auditData":{"timestamp":"2016-10-25 18:53:52.788","requestHost":"121.244.27.226","serverId":"sa3RKSJACHXE79K.env","environment":"[int]","release":"c71dde3dff5b7361b72a269a2d41e85a1aa34be0"},"error":{"code":"PRODUCT_ERROR-C94C17BE9C234F0E973A02A24882D382","message":"ProductException(5e749d40-1f0e-4395-a8d4-2d56dd2228e4, AVAILABILITY_CONFIRM, There is not enough space in the service for all the passengers.):\n"}}

**Comment by akharsh-tr** [comment]
any updates ?

**Comment by alvmunoz** [comment]
I see there were only 2 allotment available. Probably someone else booked the same room between your availability and your booking and then there weren't enough allotment.

Actually if I send the same availability request now, I don't see any availabilitiy at all of that room you tried to book. 

I guess that was a bad coincidence. Could you try again with another availability?

For example that one:

```
{
  "stay": {
    "checkIn": "2016-12-03",
    "checkOut": "2016-12-04"
  },
  "occupancies": [
    {
      "rooms": 1,
      "adults": 2,
      "children": 0
    }
  ],
  "hotels": {
    "hotel": [
      199527
      ]
  }
}

```

Returns 4 allotment, you could try with it.

**Comment by akharsh-tr** [comment]
I guess it is working , maybe you are right about allotment. 
Thanks @alvmunoz for help.

**Comment by alvmunoz** [comment]
Let us know if you find any issue
