### ISSUE TITLE
about AvailabilityRQ.shiftDays

### ISSUE THREAD

**Issue by Akasaka-win** [hotelbeds-sdk/hotel-api-sdk-Net#4]
C# source:
```
Availability avail = new Availability();
avail.checkIn = DateTime.Parse("2016/04/28");
avail.checkOut = DateTime.Parse("2016/04/30");
avail.language = "JPN";
avail.destination = "BCN";
avail.zone = 43;

AvailRoom room;
room = new AvailRoom();
room.adults = 1;
room.children = 0;
room.details = new List<RoomDetail>();
room.adultOf(30);
avail.rooms.Add(room);

AvailabilityRQ availabilityRQ = avail.toAvailabilityRQ();
Debug.WriteLine(JsonConvert.SerializeObject(availabilityRQ, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));

```
Debug output:
```
{
  "stay": {
    "checkIn": "2016-04-28",
    "checkOut": "2016-04-30",
    "shiftDays": 1,              /* <- why? */
    "allowOnlyShift": true
  },
  "occupancies": [
    {
      "rooms": 1,
      "adults": 1,
      "children": 0,
      "paxes": [
        {
          "type": "AD",
          "age": 30
        }
      ]
    }
  ],
  "destination": {
    "code": "BCN",
    "zone": 43
  },
  "language": "JPN"
}
```

I don't set avail.shiftDays.
but AvailabilityRQ.shiftDays is 1.
I don't need AvailabilityRQ.shiftDays.

So I need your help.

**Comment by alvmunoz** [comment]
That's a bug. Thanks for the report.

**Comment by Akasaka-win** [comment]
Do you plan any time be fixed?

**Comment by alvmunoz** [comment]
はい、修正する予定があります。よければ今月中。
Yes, we priorized this and it will be fixed as soon as possible. I will let you know.

**Comment by alvmunoz** [comment]
とりあえずGithubで修正しました。NuGetにアップするのはもちょっと時間がかかりますが来週もうNuGetにもアップする予定です。
We fixed it in Github, but didn't upload the package to NuGet yet.

**Comment by Akasaka-win** [comment]
修正ありがとうございました。できるだけ早いアップロードをお願いします。
Thank you fix it. Please be quickly upload as much as possible.

**Comment by alvmunoz** [comment]
NuGetにアップできました。
We uploaded this fix to NuGet.

**Comment by Akasaka-win** [comment]
キャンセルするとエラーになりました。テストはしていただいているのでしょうか？
There was an error to cancel. Do you test?

[2016-04-19 11:01:35.5907][AkasakaTest.Button1_Click] ** cancel param ** 
[2016-04-19 11:01:35.5907][AkasakaTest.Button1_Click] [
  {
    "Item1": "${bookingId}",
    "Item2": "264-421095"
  },
  {
    "Item1": "${flag}",
    "Item2": "C"
  }
] 
[2016-04-19 11:01:35.5907][AkasakaTest.Button1_Click] ** bookingCancellationRS ** 
[2016-04-19 11:01:35.5907][AkasakaTest.Button1_Click] {
  "auditData": {
    "timestamp": "2016-04-19 04:01:34.234",
    "requestHost": "118.238.248.165",
    "serverId": "sa3RKSJACHXE79K.env",
    "environment": "[int]",
    "release": "2cb1bad878d2195c9b508e2007ef96616007dacb"
  },
  "error": {
    "code": "INVALID_REQUEST-61E1AE8C43AA4894BA07BD6111FDCB36",
    "message": "The request is not compliant with the specified version of the API. Failed to convert value of type 'java.lang.String' to required type 'com.hotelbeds.hotelapi.hotelapirest.common.SimpleTypes$CancellationFlags'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type @org.springframework.web.bind.annotation.RequestParam com.hotelbeds.hotelapi.hotelapirest.common.SimpleTypes$CancellationFlags for value 'C'; nested exception is java.lang.IllegalArgumentException: No enum constant com.hotelbeds.hotelapi.hotelapirest.common.SimpleTypes.CancellationFlags.C"
  }
}

**Comment by Akasaka-win** [comment]
修正を確認しました。ありがとうございました。
I was confirmed the fix. Thank you.
