### ISSUE TITLE
Properties values are nothing or zero in booking object

### ISSUE THREAD

**Issue by dmonsilver** [hotelbeds-sdk/hotel-api-sdk-Net#40]
Hi team!

There is a lot of properties whose values are  nothing o zero in the hotelbeds.distribution.hotel_api_model.auto.model.Booking object however these properties values are present in response via direct xml call.

I.e 

JSON Serialization of  hotel_api_model.auto.model.Booking object

{"reference":"102-7113191","cancellationReference":null,"clientReference":"15893903","creationDate":"2016-11-05T00:00:00","status":"CONFIRMED","agCommision":0.0,"commisionVAT":0.0,"creationUser":"m6sps8556eejnpb8je7dnqa3","holder":{"name":"DAVID","surname":"MENDEZ BRAVO"},"hotel":{"checkIn":"2016-11-25T00:00:00","checkOut":"2016-11-26T00:00:00","code":387116,"name":"Resitur","categoryCode":null,"categoryName":null,"destinationCode":"SVQ","destinationName":null,"zoneCode":0,"zoneName":null,"latitude":null,"longitude":null,"giata":null,"keywords":null,"reviews":null,"rooms":[{"status":"CONFIRMED","code":"DBL.MT","name":null,"paxes":[{"roomId":null,"type":"AD","age":null,"name":null,"surname":null},{"roomId":null,"type":"AD","age":null,"name":null,"surname":null}],"rates":[{"rateName":null,"rateCommentsId":null,"rateComments":null,"paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":null,"cancellationPolicies":null,"taxes":null,"rateBreakDown":null,"rooms":1,"adults":0,"children":0,"childrenAges":null,"promotions":null,"offers":null,"shiftRates":null,"rateup":0.0,"rateKey":null,"rateClass":null,"rateType":null,"net":0.0,"discount":0.0,"discountPCT":0.0,"sellingRate":0.0,"hotelSellingRate":0.0,"amount":40.82,"hotelCurrency":null,"hotelMandatory":false,"dailyRates":null,"allotment":0,"commission":0.0,"commissionVAT":0.0,"commissionPCT":0.0}]}],"minRate":0.0,"maxRate":0.0,"totalSellingRate":0.0,"totalNet":0.0,"pendingAmount":0.0,"currency":null,"creditCards":null,"supplier":null,"clientComments":null,"upselling":null},"remark":null}

Direct XML response

<?xml version="1.0" encoding="UTF-8"?><bookingDetailRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages"><auditData processTime="333" timestamp="2016-11-05 18:00:36.600" requestHost="85.112.15.133" serverId="sa3RKSJACHXE79K.env" environment="[int]" release="c71dde3dff5b7361b72a269a2d41e85a1aa34be0" /><booking reference="102-7113191" clientReference="15893903" creationDate="2016-11-05" status="CONFIRMED" creationUser="m6sps8556eejnpb8je7dnqa3" totalNet="40.82" pendingAmount="40.82" currency="EUR"><modificationPolicies cancellation="true" modification="true" /><holder name="DAVID" surname="MENDEZ BRAVO" /><hotel checkIn="2016-11-25" checkOut="2016-11-26" code="387116" name="Resitur" categoryCode="3LL" categoryName="3 KEYS" destinationCode="SVQ" destinationName="Seville" zoneCode="99" zoneName="Sevilla" latitude="37.379802" longitude="-5.999955" totalNet="40.82" currency="EUR"><rooms><room status="CONFIRMED" id="1" code="DBL.DB" name="DOUBLE DOUBLE BED"><paxes><pax roomId="1" type="AD" name="David" surname="Mendez Bravo" /><pax roomId="1" type="AD" name="David" surname="Mendez Bravo" /></paxes><rates><rate rateClass="NOR" net="40.82" sellingRate="43.00" hotelMandatory="true" rateComments="in caso of double room with two children, those children will share the same bed&#xA;" paymentType="AT_WEB" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1"><cancellationPolicies><cancellationPolicy amount="40.82" from="2016-11-24T12:00:00+01:00" /></cancellationPolicies></rate></rates></room></rooms><supplier name="HOTELBEDS PRODUCT,S.L.U." vatNumber="ESB38877676" /></hotel><remark>Camas individuales por favor </remark></booking></bookingDetailRS>

Best regards 
David Montaño

**Comment by alvmunoz** [comment]
Hi @dmonsilver , sorry for the delay on this. 
Can you provide me your apikey? (not your secret).

Also, do you have the full XML response that was returned? Normally 0 or null values means that this object was empty in the XML response.  You can ignore nulls so this fields are not displayed.

**Comment by dmonsilver** [comment]
Hello alvaro,

My apikey is m6sps8556eejnpb8je7dnqa3

Sorry, In my previus post I didn't put the XML inside the tag code so was empty.  

Here is a new example of response XML and object serialization to ilustrate this issue:

Direct XML response:
`<?xml version="1.0" encoding="UTF-8"?><bookingDetailRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages"><auditData processTime="356" timestamp="2017-02-24 12:45:34.357" requestHost="87.221.174.240" serverId="sa37AUX3ROLBLIS.env" environment="[int]" release="40f9476ebdaf2b1bf1ed6c31585d2f67765b40d3" token="eef34b34-c94f-4070-8823-ee04a30c1195" /><booking reference="102-7449203" clientReference="TEST EXP." creationDate="2017-02-24" status="CONFIRMED" creationUser="m6sps8556eejnpb8je7dnqa3" totalSellingRate="45.05" totalNet="38.24" pendingAmount="38.24" currency="EUR"><modificationPolicies cancellation="true" modification="true" /><holder name="TEST GESINTUR" surname="TEST GESINTUR" /><hotel checkOut="2017-02-26" checkIn="2017-02-25" code="133288" name="Vega de Triana" categoryCode="3LL" categoryName="3 KEYS" destinationCode="SVQ" destinationName="Seville" zoneCode="72" zoneName="Camas" latitude="37.3794" longitude="-6.02862" totalSellingRate="45.05" totalNet="38.24" currency="EUR"><rooms><room status="CONFIRMED" id="1" code="APT.B1" name="APARTMENT ONE BEDROOM"><paxes><pax roomId="1" type="AD" name="TEST GESINTUR" surname="TEST GESINTUR" /><pax roomId="1" type="AD" name="TEST GESINTUR" surname="TEST GESINTUR" /></paxes><rates><rate rateKey="20170225|20170226|W|102|133288|APT.B1|NRF-TODOS|RO||1~2~0||N@0" rateClass="NRF" net="38.24" sellingRate="45.05" hotelMandatory="true" commission="5.63" commissionVAT="1.18" commissionPCT="12.50" paymentType="AT_WEB" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1"><cancellationPolicies><cancellationPolicy amount="45.05" from="2017-02-23T23:59:00+01:00" /></cancellationPolicies><rateBreakDown><rateDiscounts><rateDiscount code="NRF" name="NON REFUNDABLE DISCOUNT" amount="-7.95" /></rateDiscounts></rateBreakDown></rate></rates></room></rooms><supplier name="HOTELBEDS PRODUCT,S.L.U." vatNumber="ESB38877676" /></hotel><remark>TEST COMENTARIOS</remark></booking></bookingDetailRS>`

Object serialization from Detail Method: (no problem here it match with values from direct XML response)

`{"reference":"102-7449203","cancellationReference":null,"clientReference":"TEST EXP.","creationDate":"2017-02-24T00:00:00","status":"CONFIRMED","agCommision":0.0,"commisionVAT":0.0,"creationUser":"m6sps8556eejnpb8je7dnqa3","holder":{"name":"TEST GESINTUR","surname":"TEST GESINTUR"},"hotel":{"checkIn":"2017-02-25T00:00:00","checkOut":"2017-02-26T00:00:00","code":133288,"name":"Vega de Triana","categoryCode":"3LL","categoryName":"3 KEYS","destinationCode":"SVQ","destinationName":"Seville","zoneCode":72,"zoneName":"Camas","latitude":"37.3794","longitude":"-6.02862","giata":null,"keywords":null,"reviews":null,"rooms":[{"status":"CONFIRMED","code":"APT.B1","name":"APARTMENT ONE BEDROOM","paxes":[{"roomId":1,"type":"AD","age":null,"name":"TEST GESINTUR","surname":"TEST GESINTUR"},{"roomId":1,"type":"AD","age":null,"name":"TEST GESINTUR","surname":"TEST GESINTUR"}],"rates":[{"rateName":null,"rateCommentsId":null,"rateComments":null,"paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":"ROOM ONLY","cancellationPolicies":[{"amount":45.05,"hotelAmount":0.0,"hotelCurrency":null,"from":"2017-02-23T23:59:00+01:00"}],"taxes":null,"rateBreakDown":{"rateDiscounts":[{"code":"NRF","name":"NON REFUNDABLE DISCOUNT","amount":-7.95}],"rateSupplements":null},"rooms":1,"adults":0,"children":0,"childrenAges":null,"promotions":null,"offers":null,"shiftRates":null,"rateup":0.0,"rateKey":"20170225|20170226|W|102|133288|APT.B1|NRF-TODOS|RO||1~2~0||N@0","rateClass":"NRF","rateType":null,"net":38.24,"discount":0.0,"discountPCT":0.0,"sellingRate":45.05,"hotelSellingRate":0.0,"amount":0.0,"hotelCurrency":null,"hotelMandatory":true,"dailyRates":null,"allotment":0,"commission":5.63,"commissionVAT":1.18,"commissionPCT":12.50}]}],"minRate":0.0,"maxRate":0.0,"totalSellingRate":45.05,"totalNet":38.24,"pendingAmount":0.0,"currency":"EUR","creditCards":null,"supplier":{"name":"HOTELBEDS PRODUCT,S.L.U.","vatNumber":"ESB38877676"},"clientComments":null,"upselling":null,"cancellationAmount":0.0},"remark":"TEST COMENTARIOS"}`

Item Object serialization from List() method 
(item of com.hotelbeds.distribution.hotel_api_model.auto.messages.BookingListRS)

`{"reference":"102-7449203","cancellationReference":null,"clientReference":"TEST EXP.","creationDate":"2017-02-24T00:00:00","status":"CONFIRMED","agCommision":0.0,"commisionVAT":0.0,"creationUser":"m6sps8556eejnpb8je7dnqa3","holder":{"name":"TEST GESINTUR","surname":"TEST GESINTUR"},"hotel":{"checkIn":"2017-02-25T00:00:00","checkOut":"2017-02-26T00:00:00","code":133288,"name":"Vega de Triana","categoryCode":null,"categoryName":null,"destinationCode":"SVQ","destinationName":null,"zoneCode":0,"zoneName":null,"latitude":null,"longitude":null,"giata":null,"keywords":null,"reviews":null,"rooms":[{"status":"CONFIRMED","code":"APT.1B","name":null,"paxes":[{"roomId":1,"type":"AD","age":null,"name":null,"surname":null},{"roomId":1,"type":"AD","age":null,"name":null,"surname":null}],"rates":[{"rateName":null,"rateCommentsId":null,"rateComments":null,"paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":null,"cancellationPolicies":null,"taxes":null,"rateBreakDown":null,"rooms":1,"adults":0,"children":0,"childrenAges":null,"promotions":null,"offers":null,"shiftRates":null,"rateup":0.0,"rateKey":null,"rateClass":null,"rateType":null,"net":0.0,"discount":0.0,"discountPCT":0.0,"sellingRate":0.0,"hotelSellingRate":0.0,"amount":45.05,"hotelCurrency":null,"hotelMandatory":false,"dailyRates":null,"allotment":0,"commission":0.0,"commissionVAT":0.0,"commissionPCT":0.0}]}],"minRate":0.0,"maxRate":0.0,"totalSellingRate":0.0,"totalNet":0.0,"pendingAmount":0.0,"currency":null,"creditCards":null,"supplier":null,"clientComments":null,"upselling":null,"cancellationAmount":0.0},"remark":null}`

As you can note, the hotelbeds.distribution.hotel_api_model.auto.model.Booking objects has almost all properties value at zero or null. This not happend with the hotelbeds.distribution.hotel_api_model.auto.messages.BookingDetailRS object returned by 'Detail' method

Best regards 
David.

**Comment by dmonsilver** [comment]
Hello Any advance to this issue?

**Comment by vmavromatis** [comment]
Hello @dmonsilver we apologise for the delay in the response. In order to deserialize each object coming from inside 'bookings' of the Booking List an object of type  **hotelbeds.distribution.hotel_api_model.auto.model.Booking** should work. Here is an example from my computer:
![image](https://user-images.githubusercontent.com/8668731/34252517-4b70ae68-e644-11e7-9e62-5a14bbcb69b2.png)

You can see that there are fields returned (reference, creationUser, status etc). Try to use the loop I used. Here's the code for your reference:

```c#
param = new List<Tuple<string, string>>
{
	new Tuple<string, string>("${start}", DateTime.Now.AddDays(-30).ToString("yyyy-MM-dd")),
	new Tuple<string, string>("${end}", DateTime.Now.ToString("yyyy-MM-dd")),
	new Tuple<string, string>("${includeCancelled}", "true"),
	new Tuple<string, string>("${filterType}", "CREATION"),
	new Tuple<string, string>("${from}", "1"),
	new Tuple<string, string>("${to}", "25"),
};

BookingListRS bookingListRS = client.List(param);
if (bookingListRS != null)
{
	Console.WriteLine(JsonConvert.SerializeObject(bookingListRS, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));
	Console.WriteLine(bookingListRS.bookings);
	foreach (com.hotelbeds.distribution.hotel_api_model.auto.model.Booking booking in bookingListRS.bookings.bookings)
	{
		param = new List<Tuple<string, string>>
		{
			new Tuple<string, string>("${bookingId}", booking.reference)
		};
		BookingDetailRS bookingDetailRS = client.Detail(param);
		if (bookingDetailRS != null)
		{
			Console.WriteLine(JsonConvert.SerializeObject(bookingDetailRS, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));
			Console.WriteLine(bookingDetailRS.booking);
		}
	}
}

```

Please also make sure 'bookings' inside List has any objects at all. Hope this helps and again sorry for the slow reply.

**Comment by vmavromatis** [comment]
I will now be closing this. Please feel free to comment if you want to re-open.
Regards
