### ISSUE TITLE
ShiftDays are always set true

### ISSUE THREAD

**Issue by akharsh-tr** [hotelbeds-sdk/hotel-api-sdk-Net#44]
See hotel-api-sdk/helpers/Availability.cs,

availabilityRQ.stay = new Stay(checkIn, checkOut, shiftDays, true);
here true is hard coded , even if you do not request.

**Comment by alvmunoz** [comment]
Hi @akharsh-tr ,

This hard coded "true" is not to request ShiftDays. Actually as you can see, if you don't ask for ShiftDays you won't receive them. 

This true means: "even if there is no availability for the specified dates, show the shiftDays (in case you requested them)".

**Comment by akharsh-tr** [comment]
Yeah, my mistake. 
I was wondering why we are sending "allowOnlyShift": true always even if we have not requested that.
