### ISSUE TITLE
HotelApiClient Error

### ISSUE THREAD

**Issue by alifindik** [hotelbeds-sdk/hotel-api-sdk-Net#46]
Hello,

I'm having this error while i try to initiate HotelApiClient. (" HotelApiClient client = new HotelApiClient();")

"HotelApiClient cannot be created without specifying an API key, Shared Secret, the Hotel API version and the service you are connecting to"

Here is my web.config file app settings. I have my ApiKey and Secret.

` <appSettings>    
      <add key="ApiKey" value="My APi Key Here" />
      <add key="SharedSecret" value="My Secret Here" />
      <add key="ENVIRONTMENT" value="TEST" />
      <add key="TEST" value="https://api.test.hotelbeds.com/hotel-api" />
      <add key="LIVE" value="https://api.hotelbeds.com/hotel-api" />
      <add key="DEVELOPMENT" value="http://localhost:8181" />    
  </appSettings>
`

**Comment by alvmunoz** [comment]
Hi @alifindik  , 
There was a typo. We released version 0.6.7 with the fix.  You can copy the new config file from there.
