### ISSUE TITLE
Distribution of pax is not correct

### ISSUE THREAD

**Issue by imaadhrizni** [hotelbeds-sdk/hotel-api-sdk-Net#48]
`{
   "holder":{
      "name":"Rosetta",
      "surname":"Pruebas(Test Environment)"
   },
   "rooms":[
      {
         "paxes":[
            {
               "roomId":1,
               "type":"AD",
               "age":30,
               "name":"Irri",
               "surname":"asdasd"
            },
            {
               "roomId":1,
               "type":"CH",
               "age":15,
               "name":"Times",
               "surname":"TravelC11"
            },
            {
               "roomId":1,
               "type":"CH",
               "age":13,
               "name":"Times",
               "surname":"TravelC12"
            },
            {
               "roomId":1,
               "type":"CH",
               "age":9,
               "name":"Times",
               "surname":"TravelC13"
            }
         ],
         "rateKey":"20170220|20170227|W|164|145403|QUA.ST|NRF-BAR|GB||1~1~3|15~13~9|N@3BB8D1AE453F420BB732956E10F59DB1"
      },
      {
         "paxes":[
            {
               "roomId":1,
               "type":"AD",
               "age":30,
               "name":"we",
               "surname":"qwe"
            }
         ],
         "rateKey":"20170220|20170227|W|164|145403|SGL.ST|NRF-BAR|GB||1~1~0||N@3BB8D1AE453F420BB732956E10F59DB1"
      }
   ],
   "paymentData":null,
   "clientReference":"FjO5Dvl3ZEuHxCKOj1j",
   "remark":"***SDK***TESTING",
   "echoToken":null,
   "language":null
}
`
When trying to confirm the above booking I'm receiving an error response with the following: "Invalid data. Error at property rooms: The distribution of paxes is not correct. The number of rooms specified in the paxes do not match with the requested ones".

**Comment by imaadhrizni** [comment]
`{
"holder":{
"name":"Rosetta",
"surname":"Pruebas(Test Environment)"
},
"rooms":[
{
"paxes":[
{
"roomId":1,
"type":"AD",
"age":30,
"name":"Irri",
"surname":"asdasd"
},
{
"roomId":1,
"type":"CH",
"age":15,
"name":"Times",
"surname":"TravelC11"
},
{
"roomId":1,
"type":"CH",
"age":13,
"name":"Times",
"surname":"TravelC12"
},
{
"roomId":1,
"type":"CH",
"age":9,
"name":"Times",
"surname":"TravelC13"
}
],
"rateKey":"20170220|20170227|W|164|145403|QUA.ST|NRF-BAR|GB||113|15139|N@3BB8D1AE453F420BB732956E10F59DB1"
},
{
"paxes":[
{
"roomId":1,
"type":"AD",
"age":30,
"name":"we",
"surname":"qwe"
}
],
"rateKey":"20170220|20170227|W|164|145403|SGL.ST|NRF-BAR|GB||110||N@3BB8D1AE453F420BB732956E10F59DB1"
}
],
"paymentData":null,
"clientReference":"FjO5Dvl3ZEuHxCKOj1j",
"remark":"***SDK***TESTING",
"echoToken":null,
"language":null
}`

**Comment by alvmunoz** [comment]
hi @imaadhrizni , 2 questions:
a) are you using the SDK?
b) Can you show me the /hotels/ request too?

**Comment by imaadhrizni** [comment]
@alvmunoz sorry for such a late reply but I'm not working on that project anymore. Could you please close this delete this issue and sorry for the inconvenience.
