### ISSUE TITLE
The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by kumarpramod3** [hotelbeds-sdk/hotel-api-sdk-Net#49]
**# Hi,

We are trying to send the request  and using the same sample code which is mentioned in apitude document but still we are getting error message. 

API Key: j486gzt46q8vv4ee3tscmb5p

Endpoint: https://api.test.hotelbeds.com/hotel-api/1.0/hotels

![sample code screen](https://cloud.githubusercontent.com/assets/26443493/23967519/2ec9e054-09e5-11e7-9526-fb23ff9b4b33.jpg)
[APITude.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-Net/files/845803/APITude.txt)

**Comment by alvmunoz** [comment]
Hi, we did a small change #50 
Can you update the SDK and try again?

Thanks,

**Comment by vmavromatis** [comment]
Hi @kumarpramod3, I will be closing this now as it seems to be resolved. Feel free to re-open in case you'd run into any more problems.
