### ISSUE TITLE
about AvailRoom.children

### ISSUE THREAD

**Issue by Akasaka-win** [hotelbeds-sdk/hotel-api-sdk-Net#5]
I want availability check "1room 1ADT+1CHD".

C# source:
```
Availability avail = new Availability();
avail.checkIn = DateTime.Parse("2016/04/28");
avail.checkOut = DateTime.Parse("2016/04/30");
avail.language = "JPN";
avail.destination = "BCN";
avail.zone = 43;

AvailRoom room;
room = new AvailRoom();
room.adults = 1;
room.children = 1;
room.details = new List<RoomDetail>();
room.adultOf(30);
room.childOf(4);
avail.rooms.Add(room);

AvailabilityRQ availabilityRQ = avail.toAvailabilityRQ();
```
Exception raised at avail.toAvailabilityRQ.

```
[ArgumentException: Children must be 1 or greater]
   com.hotelbeds.distribution.hotel_api_sdk.helpers.Availability.toAvailabilityRQ() in D:\Multinucleo\GitHub\hotel-api-sdk-Net\hotel-api-sdk\helpers\Availability.cs:299

```
Please tell me why.

**Comment by alvmunoz** [comment]
The children verification is wrong. I will let you know once it is fixed.
Thanks.

**Comment by Akasaka-win** [comment]
Do you plan any time be fixed?

**Comment by alvmunoz** [comment]
Yes, we priorized this and it will be fixed as soon as possible. I will let you know.

**Comment by alvmunoz** [comment]
とりあえずGithubで修正しました。NuGetにアップするのはもちょっと時間がかかりますが来週もうNuGetにもアップする予定です。
We fixed it in Github, but didn't upload the package to NuGet yet.

**Comment by Akasaka-win** [comment]
修正ありがとうございました。できるだけ早いアップロードをお願いします。
Thank you fix it. Please be quickly upload as much as possible.

**Comment by alvmunoz** [comment]
NuGetにアップできました。
We uploaded this fix to NuGet.

**Comment by alvmunoz** [comment]
@Akasaka-win , 確認できましたか？

**Comment by Akasaka-win** [comment]
修正を確認しました。ありがとうございました。
I was confirmed the fix. Thank you.
