### ISSUE TITLE
No available hotels in test environment

### ISSUE THREAD

**Issue by dcerda83** [hotelbeds-sdk/hotel-api-sdk-Net#53]
Hi,
I have tried a lot to get any available hotel by using different dates but always returns "total": 0.
I've been looking for hotels in NYC and MIA by using 1 night and 2 adults on: next week, next month, 2 months, 3 months... but nothing.

Here is my request for hotels in NYC (60 codes):

{
	"language": "CAS",
	"stay": {
		"checkIn": "2017-11-22",
		"checkOut": "2017-11-25"
	},
	"occupancies": [{
			"rooms": 1,
			"adults": 2,
			"children": 0,
			"paxes": [{
					"type": "AD",
					"age": 30
				},
				{
					"type": "AD",
					"age": 30
				}
			]
		}
	],
	"hotels": {
		"hotel": [12776, 12857, 12998, 12999, 13000, 13001, 13002, 13003, 13005, 13006, 13007, 13009, 13010, 13011, 13013, 13014, 13015, 13016, 13017, 13018, 13021, 13022, 13023, 13054, 13055, 13057, 13059, 13060, 13061, 13248, 13380, 13381, 13382, 13384, 13385, 13386, 13388, 13391, 13392, 13393, 13395, 13397, 13398, 13437, 13438, 13439, 13440, 13442, 13445, 13446, 13448, 13449, 13451, 13452, 13453, 13457, 13458, 14739, 14740, 14742, 14755, 14778, 14790, 14797, 14808, 14825]
	},
	"dailyRate": true
}

Endpoint: https://api.test.hotelbeds.com/hotel-api/1.0/hotels

Thanks in advance.

**Comment by vmavromatis** [comment]
This definitely sounds server-side related, there was the exact same issue on INT on Wednesday after the clone from LIVE but it was resolved. I will try to reproduce and let you know.

**Comment by vmavromatis** [comment]
I was able to reproduce, however I will be closing this now as this is not directly related to the SDK. The backend team have been made aware and working on a solution. I will provide an update here if anything changes, or you can contact them further using apitude@hotelbeds.com. Let me know if you need any more help.
