### ISSUE TITLE
about HotelApiClient.confirm()

### ISSUE THREAD

**Issue by Akasaka-win** [hotelbeds-sdk/hotel-api-sdk-Net#6]
C# source:
```
BookingRS responseBooking = client.confirm(bookingRQ);
if (responseBooking != null)
    Console.WriteLine(JsonConvert.SerializeObject(responseBooking, Formatting.Indented, new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore }));
else
    Console.WriteLine("ResponseBooking Object Response is null");   /* <- here */
```

What is the reason that responseBooking  is NULL.
I'd clear if there is responseBooking.error value....

So I need your help.

**Comment by alvmunoz** [comment]
@Akasaka-win 
In case there is a Gateway 504 timeout, you will receive an empty response. 
This uses to happen in the TEST server. You don't have this problem often in production but you better treat that situation too.

**Comment by Akasaka-win** [comment]
I understand. Thank you.
